# Generated by Django 3.1.5 on 2021-04-28 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookmarks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file_path', models.FilePathField(path='/home/dominik/projects/dpins_extra/media')),
                ('date_taken', models.DateTimeField(auto_now_add=True)),
                ('bookmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_archives', to='bookmarks.bookmark')),
            ],
        ),
        migrations.CreateModel(
            name='SinglePageArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html_file_path', models.FilePathField(path='/home/dominik/projects/dpins_extra/media')),
                ('date_taken', models.DateTimeField(auto_now_add=True)),
                ('bookmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_archives', to='bookmarks.bookmark')),
            ],
        ),
        migrations.CreateModel(
            name='MediaArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_file_path', models.FilePathField(path='/home/dominik/projects/dpins_extra/media')),
                ('date_taken', models.DateTimeField(auto_now_add=True)),
                ('bookmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_archives', to='bookmarks.bookmark')),
            ],
        ),
    ]
