# Generated by Django 3.1.5 on 2021-04-29 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archiver', '0002_singlepagearchive_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediaarchive',
            name='media_file_path',
        ),
        migrations.RemoveField(
            model_name='singlepagearchive',
            name='html_file_path',
        ),
        migrations.RemoveField(
            model_name='videoarchive',
            name='video_file_path',
        ),
    ]
