# Generated by Django 3.1.5 on 2021-04-29 22:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('archiver', '0003_auto_20210429_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaarchive',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='videoarchive',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
