# Generated by Django 3.1.5 on 2021-04-30 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiver', '0005_videoarchive_extension'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoarchive',
            name='extension',
        ),
        migrations.AddField(
            model_name='videoarchive',
            name='file_name',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
