# Generated by Django 3.1.5 on 2021-04-30 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiver', '0007_auto_20210430_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaarchive',
            name='file_path',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='singlepagearchive',
            name='file_path',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
