# Generated by Django 3.1.5 on 2021-04-30 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archiver', '0008_auto_20210430_2109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mediaarchive',
            old_name='file_path',
            new_name='rel_file_path',
        ),
        migrations.RenameField(
            model_name='singlepagearchive',
            old_name='file_path',
            new_name='rel_file_path',
        ),
        migrations.RenameField(
            model_name='videoarchive',
            old_name='file_path',
            new_name='rel_file_path',
        ),
    ]
