# Generated by Django 3.1.5 on 2021-05-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiver', '0009_auto_20210430_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoarchive',
            name='title',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
